### PR TITLE
user input validation and rate limiting implemented

### PR DESCRIPTION
**Pull request by rohteemie**

### CODE REVIEW

**Comment by Adeleye080** [comment]
@rohteemie 
Looks like there is a conflict.
Please have it resolved.

**Comment by rohteemie** [comment]
@Adeleye080 
Conflict is now Resolved

**Comment by Adeleye080** [comment]
@rohteemie 
Another conflict has been detected sir

**Review by rohteemie — COMMENTED** [review]
reviewd

**Pull request merged**
