### PR TITLE
Feature/message model

### PR DESCRIPTION
**Pull request by Adeleye080**
defined the message model

### CODE REVIEW

**Review by rohteemie — APPROVED** [review]

**Review by rohteemie — CHANGES_REQUESTED** [review]
Check the object imported from database module in the message model module
sequelize instead of storage.

You may need to check the updatedAt and createdAt field define in the User model module, as they are already taken care of in sequelize by default.

**Comment by Adeleye080** [comment]
Yeah, I already corrected the timestamps in the #14 pull request.

**Comment by Adeleye080** [comment]
@rohteemie 
I want to remind you that you haven't created PR for the amendment you made in the database modul

**Comment by Adeleye080** [comment]
@rohteemie 
Requested corrections are made.

**Review by rohteemie — APPROVED** [review]

**Pull request merged**
